### PR TITLE
Add ability to resolve packages in alternate pypi urls.

### PR DESCRIPTION
**Pull request by tomdottom**
Finder now updates itself with options found in requirements.txt

New test case primarily focuses on:
  --index-url
  --extra-index-url
  --trusted-host

### CODE REVIEW

**Comment by alanhamlett** [comment]
Thanks!

**Comment by tomdottom** [comment]
No problem. Nice idea for a project.

I did, however, find the tests very mocky and hard to get to grips with.
Not that I can talk as I did nothing to improve it :disappointed: 

Cheers again.

**Comment by alanhamlett** [comment]
Would be open to PRs if you see ways to improve the tests. Thanks again!

**Comment by tomdottom** [comment]
Will see if I can send some your way when I've got an hour or two spare.

**Comment by alanhamlett** [comment]
Added you as a contributor in the AUTHORS file.

**Pull request merged**
